
// This file has been generated by the GUI designer. Do not modify.
namespace ExamPrepper
{
	public partial class QuizWindow
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView questionTextview;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		
		private global::Gtk.TextView userResponseTextview;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		
		private global::Gtk.TextView answerTextview;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Button rejectAnswerButton;
		
		private global::Gtk.Button showAnswerButton;
		
		private global::Gtk.Button acceptAnswerButton;
		
		private global::Gtk.Label progressText;
		
		private global::Gtk.ProgressBar progressbar;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ExamPrepper.QuizWindow
			this.Name = "ExamPrepper.QuizWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("QuizWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ExamPrepper.QuizWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.questionTextview = new global::Gtk.TextView ();
			this.questionTextview.Buffer.Text = "Quiz Window\n";
			this.questionTextview.CanFocus = true;
			this.questionTextview.Name = "questionTextview";
			this.questionTextview.Editable = false;
			this.questionTextview.CursorVisible = false;
			this.questionTextview.AcceptsTab = false;
			this.questionTextview.WrapMode = ((global::Gtk.WrapMode)(3));
			this.GtkScrolledWindow.Add (this.questionTextview);
			this.vbox2.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow]));
			w2.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.userResponseTextview = new global::Gtk.TextView ();
			this.userResponseTextview.CanFocus = true;
			this.userResponseTextview.Name = "userResponseTextview";
			this.userResponseTextview.WrapMode = ((global::Gtk.WrapMode)(3));
			this.GtkScrolledWindow1.Add (this.userResponseTextview);
			this.vbox2.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow1]));
			w4.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.answerTextview = new global::Gtk.TextView ();
			this.answerTextview.CanFocus = true;
			this.answerTextview.Name = "answerTextview";
			this.answerTextview.Editable = false;
			this.answerTextview.CursorVisible = false;
			this.answerTextview.AcceptsTab = false;
			this.answerTextview.WrapMode = ((global::Gtk.WrapMode)(3));
			this.GtkScrolledWindow2.Add (this.answerTextview);
			this.vbox2.Add (this.GtkScrolledWindow2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow2]));
			w6.Position = 2;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.rejectAnswerButton = new global::Gtk.Button ();
			this.rejectAnswerButton.CanFocus = true;
			this.rejectAnswerButton.Name = "rejectAnswerButton";
			this.rejectAnswerButton.UseUnderline = true;
			this.rejectAnswerButton.Label = global::Mono.Unix.Catalog.GetString ("Reject answer");
			this.hbox1.Add (this.rejectAnswerButton);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.rejectAnswerButton]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.showAnswerButton = new global::Gtk.Button ();
			this.showAnswerButton.CanFocus = true;
			this.showAnswerButton.Name = "showAnswerButton";
			this.showAnswerButton.UseUnderline = true;
			this.showAnswerButton.Label = global::Mono.Unix.Catalog.GetString ("Show answer");
			this.hbox1.Add (this.showAnswerButton);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.showAnswerButton]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.acceptAnswerButton = new global::Gtk.Button ();
			this.acceptAnswerButton.CanFocus = true;
			this.acceptAnswerButton.Name = "acceptAnswerButton";
			this.acceptAnswerButton.UseUnderline = true;
			this.acceptAnswerButton.Label = global::Mono.Unix.Catalog.GetString ("Accept answer");
			this.hbox1.Add (this.acceptAnswerButton);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.acceptAnswerButton]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.progressText = new global::Gtk.Label ();
			this.progressText.Sensitive = false;
			this.progressText.Name = "progressText";
			this.progressText.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.hbox1.Add (this.progressText);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.progressText]));
			w10.PackType = ((global::Gtk.PackType)(1));
			w10.Position = 3;
			w10.Expand = false;
			w10.Fill = false;
			w10.Padding = ((uint)(2));
			// Container child hbox1.Gtk.Box+BoxChild
			this.progressbar = new global::Gtk.ProgressBar ();
			this.progressbar.Sensitive = false;
			this.progressbar.Name = "progressbar";
			this.hbox1.Add (this.progressbar);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.progressbar]));
			w11.PackType = ((global::Gtk.PackType)(1));
			w11.Position = 4;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 659;
			this.DefaultHeight = 605;
			this.Show ();
			this.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler (this.OnWindowKeyRelease);
			this.rejectAnswerButton.Clicked += new global::System.EventHandler (this.OnRejectAnswerButtonClicked);
			this.showAnswerButton.Clicked += new global::System.EventHandler (this.OnShowAnswerButtonClicked);
			this.acceptAnswerButton.Clicked += new global::System.EventHandler (this.OnAcceptAnswerButtonClicked);
		}
	}
}
