
// This file has been generated by the GUI designer. Do not modify.
namespace ExamPrepper
{
	public partial class ImageDisplayerWindow
	{
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Image imageArea;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ExamPrepper.ImageDisplayerWindow
			this.Name = "ExamPrepper.ImageDisplayerWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("ImageDisplayerWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ExamPrepper.ImageDisplayerWindow.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.imageArea = new global::Gtk.Image ();
			this.imageArea.Name = "imageArea";
			this.hbox1.Add (this.imageArea);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.imageArea]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
